C
C     PROGRAMA SECCION-OFSET (nudos)
C     ==============================
C
C     ESTE PROGRAMA CALCULA, A PARTIR DE LA SALIDA DE UN F.E.M. EJECUTADO
C     CON EL PROGRAMA NASTRAN, LAS CARGAS RESULTANTES SOBRE UNA SECCION:
C     MOMENTO FLECTOR, FUERZA AXIAL Y FUERZA CORTANTE EN EL PRIMER NUDO
C     QUE SE LISTE EN LA SECCION.
C	LAS TRASLADA A UN PUNTO DE LA SECCION A UNA DISTANCIA 'OFSET'
C	MEDIDA DESDE EL REVESTIMIENTO. SE DEBE DEFINIR DESDE EL PRIMER NUDO DE LA
C	SECCION, QUE DEBE ESTAR EN EL REVESTIMIENTO.
C
C	EL EJE 'X' DEBE SER EL LONGITUDINAL DE LA CUADERNA HACIA AFUERA DE LA SECCION Y
C	EL EJE 'Y' HACIA EL INTERIOR DEL AVION CONTENIDO EN LA SECCION A ESTUDIAR.
C
C	SI EL OFSET VALE 0.0 NO SE HACE SELECCION DE MAXIMOS Y MINIMOS.
C
C	EL SISTEME DE EJES LOCALES DE CADA SECCION SE PUEDE DEFINIR CON 
C	UNOS NUDOS DOFERENTES A LOS DE LA SECCION.
C
C	ELIMINA CASOS DE CARGA SI SE PONEN NUMEROS NEGATIVOS
C
C     LEE ELEMENTOS 'CONROD'
C
C     LA CABECERA SE LEE DE UN FICHERO APARTE.
C
C     ESTE PROGRAMA LEE TODAS LAS COMPONENTES.
C
C
C     LEE 'MSC.' O 'MSC/' O 'MSC ' PARA LOCALIZAR EL FINAL DE LAS TABLAS.
C	
C	AVISA SI HAY EJES LOCALES EN LOS NUDOS
C
C     TIENE INCORPORADA LA POSIBILIDAD DE PONER '0' EN EL NÚMERO DE CASOS 
C     DE CARGA A PROCESAR. EN ESTE CASO PROCESA TODOS LOS EXISTENTES EN
C     EL FICHERO .F06
C
C
C     YA ESTA CORREGIDO EL FORMATO DE LECTURA DE ELEMENTOS
C     (QUITAR EL FORMATO LIBRE)
C
C     DEBE EXISTIR EN EL FICHERO DE ENTRADA EL "ECHO" DEL BULK DATA
C     DE NASTRAN Y LA SALIDA COMPLETA DE "GRID POINT FORCE BALANCE"
C     PARA LOS CASOS DE CARGA DE INTERES. EL RESTO DE LA SALIDA DEL
C     PROGRAMA NASTRAN NO ES NECESARIA.
C
C
C     LAS COORDENADAS DE LOS NUDOS DEBEN ESTAR EN EL SISTEMA GLOBAL O
C     EN EL LOCAL (HELICE) IDENTIFICADO CON EL NUMERO (8)
C     EN EL LOCAL (RAMPA Y PORTALON CN235) NUMERO (1)
C
C
C     LAS SECCIOINES DEBEN SER PLANAS O PRACTICAMENTE PLANAS
C
C    
C     NOTA: ESTA VERSION TIENE CORREGIDO EL ERROR QUE HABIA CON LOS 
C     ====  EJES LOCALES. ( LA TABLA 'GPFB' ESTA DADA EN EL SISTEMA
C           DE EJES DEFINIDO PARA EL DESPLAZAMIENTO DE CADA NUDO )
C
C
C
C     LIMITACIONES:
C
C     -  1501 NUDOS EN .DAT  (REPETIDOS)
C     -  100002 ELEMENTOS
C     -  103 SECCIONES
C     -  2004 CASOS DE CARGA POR SECCCION
C     -  1005 NUDOS EN CADA SECCION
C     -  56 ELEMENTOS CONECTADOS A UN NUDO
C     -  2004 CASOS DE CARGA EN EL FICHERO XXX.F06
C
C
C
C      IMPLICIT NONE
C      INTEGER*4 N_MAX_NUDOS_DAT, N_MAX_EMENTOS,N_MAX_NUDOS_F06
C      INTEGER*4 N_MAX_CASOS_F06, N_MAX_CASOS_DAT
C      INTEGER*4 N_MAX_LOCS, N_MAX_NUDOSxLOC
C      INTEGER*4 N_MAX_ELEM_1NUDO, N_MAX_ELEM_2NUDO
C      INTEGER*4 N_MAX_CELAS, N_MAX_NUDOS_CELAS
C
C
C
C
      PARAMETER (N_MAX_NUDOS_DAT=1501)
      PARAMETER (N_MAX_ELEMENTOS=100002)
      PARAMETER (N_MAX_CASOS_F06=2004)
      PARAMETER (N_MAX_CASOS_DAT=2004)
      PARAMETER (N_MAX_LOCS=103)
      PARAMETER (N_MAX_NUDOSxLOC=1005)
      PARAMETER (N_MAX_ELEM_1NUDO=56)
      PARAMETER (N_MAX_ELEM_2NUDO=56)
C
C
C      PARAMETER (N_MAX_NUDOS_F06=3000)
C      PARAMETER (N_MAX_CELAS=1000)
C      PARAMETER (N_MAX_NUDOS_CELAS=2000)
C
C
C
C
C
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C
      DIMENSION IELEM(N_MAX_ELEMENTOS),ICONEC(N_MAX_ELEMENTOS,4),
     +NUDO(N_MAX_NUDOS_DAT),
     +RCOOR(N_MAX_NUDOS_DAT,3),
     +ICONNUD(N_MAX_NUDOS_DAT,N_MAX_ELEM_1NUDO),
     +RFUERZA(N_MAX_NUDOS_DAT,N_MAX_ELEM_1NUDO,6),
     +IELSEL(N_MAX_LOCS,N_MAX_CASOS_DAT,N_MAX_ELEM_1NUDO),
     +NUMCASOS(N_MAX_LOCS),NCAS(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +NUMNUDA(N_MAX_LOCS),NNUDA(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +NUMNUDB(N_MAX_LOCS),
     +NNUDB(N_MAX_LOCS,N_MAX_NUDOSxLOC),NG1(N_MAX_LOCS),NG2(N_MAX_LOCS),
     +NG3(N_MAX_LOCS),RLCOSALF(N_MAX_LOCS),
     +RLCOSBET(N_MAX_LOCS),
     +RLCOSGAM(N_MAX_LOCS),RTCOSALF(N_MAX_LOCS),RTCOSBET(N_MAX_LOCS),
     +RTCOSGAM(N_MAX_LOCS),
     +RLT(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +RTT(N_MAX_LOCS,N_MAX_NUDOSxLOC),IICASE(N_MAX_CASOS_DAT),
     +RZT(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +RMOMENTL(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +ICASEL(N_MAX_CASOS_DAT),RZCOSALF(N_MAX_LOCS),RZCOSBET(N_MAX_LOCS),
     +RZCOSGAM(N_MAX_LOCS),
     +IEJES(N_MAX_NUDOS_DAT),
     +INUDO(N_MAX_NUDOS_DAT),INUMCASOS(N_MAX_LOCS),ROFSET(N_MAX_LOCS),
     +RTDIST(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +RLDISL(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +RZDISZ(N_MAX_LOCS,N_MAX_NUDOSxLOC),
     +RMOMENTT(N_MAX_LOCS,N_MAX_CASOS_DAT),
     +RMOMENTZ(N_MAX_LOCS,N_MAX_CASOS_DAT),
     +RFLECTOR(N_MAX_CASOS_DAT),RCORTANTE(N_MAX_CASOS_DAT),
     +RTORSOR(N_MAX_CASOS_DAT)  
C
      CHARACTER*1   ABIT
      CHARACTER*11  ALFA1
      CHARACTER*14  ALFA4
      CHARACTER*4   ALINE1,ALINE4,ALFA5
      CHARACTER*3   ALFA3
      CHARACTER*48  ALINE2
      CHARACTER*40  ACASO
      CHARACTER*40  CASO(N_MAX_CASOS_DAT)
      CHARACTER*28  ALINE3
      CHARACTER*90  ALINE5
      CHARACTER*8   ALFA2
      CHARACTER*70  ATITULO
      CHARACTER*70  FILEINCAB
      CHARACTER*70  FILEINF06
      CHARACTER*70  FILEINDAT
      CHARACTER*70  FILEOUT
C
      NE=0       ! 'NE' ES EL NUMERO TOTAL DE ELEMENTOS
      NC=1       ! 'NC' ES EL NUMERO TOTAL DE CASOS DE CARGA
      NEAUX=0    ! 'NC' ES UN CONTADOR AUXILIAR DE ELEMENTOS UNIDOS A
C                   UN NUDO
      NBIT1=0    !  PARAMETRO PARA FACILITAR LA CUENTA DE CASOS DE CARGA
      CASO(1)='HYTUFDER456GFCVGHUYIOP09KHY65C'
      NBIT2=0
      NBIT3=0
      NBIT4=1
      NBIT5=0
      NBIT6=0
      NBIT7=0
      NBIT8=1   ! COMPRUEBA SI LA SIGUIENTE TABLA ES 'B A L A N C E'
      NNUR=0    ! NUMERO DE NUDOS EN EL FICHERO .DAT  (REPETIDOS)
      NNURR=0
C 
C
      WRITE(6,103)
  103 FORMAT(/,' FICHERO CABECERA : ',$)
      READ(5,200)FILEINCAB
C
      WRITE(6,100)
  100 FORMAT(/,' FICHERO .F06 : ',$)
      READ(5,200)FILEINF06
  200 FORMAT(A)
C
      WRITE(6,101)
  101 FORMAT(/,' FICHERO .DAT : ',$)
      READ(5,201)FILEINDAT
  201 FORMAT(A)
C
      WRITE(6,102)
  102 FORMAT(/,' FICHERO .RES : ',$)
      READ(5,202)FILEOUT
  202 FORMAT(A)
C
      OPEN (9,FILE=FILEINCAB,STATUS='OLD')
      OPEN (10,FILE=FILEINF06,STATUS='OLD')
      OPEN (11,FILE=FILEINDAT,STATUS='OLD')
      OPEN (12,FILE=FILEOUT,STATUS='NEW')
C
C
C
C
C
C     
C     LECTURA DEL FICHERO DE ENTRADA CON LOS DATOS DE LAS SECCIONES A
C     PROCESAR
C     =================================================================
C
C
C
      READ(11,1054)ATITULO
 1054 FORMAT(/,/,/,7X,A70)
C
C
      READ(11,1500)NUMSEC       ! NUMERO DE SECCIONES A PROCESAR
 1500 FORMAT(/,I8)
C******************************************
C      WRITE(12,3000)NUMSEC
C 3000 FORMAT(/,2X,'NUMERO DE SECCIONES  ',I8)
C******************************************
C
      DO 700 I=1,NUMSEC
C
      READ(11,1505)INUMCASOS(I)     ! NUMERO DE CASOS DE CARGA PARA LA
 1505 FORMAT(/,/,/,/,I8)            ! SECCION  I
	NUMCASOS(I)=ABS(INUMCASOS(I))	! PARA QUITAR CASOS CON NUMEROS NEGATIVOS
C
      IF(INUMCASOS(I).EQ.0) GO TO 706    ! SI EN EL NUMERO DE CASOS SE PONE 0
C
C
C
      DO 705 J=1,NUMCASOS(I)
C
      READ(11,1510)NCAS(I,J)    ! LISTA DE CASOS DE GARGA
 1510 FORMAT(I8)
C************************************
C      WRITE(12,3005)I,NUMCASOS(I),NCAS(I,J)
C 3005 FORMAT(/,'SECCION: ',I3,5X,'CASOS:',I3,3X,'CASO:',I3)
C************************************
C
  705 CONTINUE
  706 CONTINUE
C
      READ(11,1515)NUMNUDA(I)   ! NUMERO DE NUDOS DE LA SECCION
 1515 FORMAT(/,I8)
C
      DO 710 K=1,NUMNUDA(I)
C
      READ(11,1520)NNUDA(I,K)   ! LISTA DE LOS NUDOS DE LA SECCION
 1520 FORMAT(I8) 
C**************************************
C      WRITE(12,3010)I,NUMNUDA(I),NNUDA(I,K)
C 3010 FORMAT(/,'SECCION: ',I3,5X,'NUDOS A:',I3,3X,'NUDO A:',I5)
C**************************************
C
C
      NNUR=NNUR+1
      INUDO(NNUR)=NNUDA(I,K)
C
C
  710 CONTINUE
C
C
	READ(11,1521)ROFSET(I)    ! LEE EL OFSET DE CADA SECCION XXXXXXXXX
 1521 FORMAT(F8.3)
C
C
      READ(11,1525)NUMNUDB(I)   ! NUMERO DE NUDOS AL OTRO LADO DE LA
 1525 FORMAT(/,I8)              ! SECCION
C
      DO 715 L=1,NUMNUDB(I)
C
      READ(11,1530)NNUDB(I,L)   ! LISTA DE LOS NUDOS
 1530 FORMAT(I8)
C**************************************
C      WRITE(12,3011)I,NUMNUDB(I),NNUDB(I,L)
C 3011 FORMAT(/,'SECCION: ',I3,5X,'NUDOS B:',I3,3X,'NUDO B:',I5)
C**************************************
C
C
      NNUR=NNUR+1
      INUDO(NNUR)=NNUDB(I,L)
C
C
  715 CONTINUE
C
C
C
      READ(11,1535)NG1(I),NG2(I),NG3(I)  ! DEFINICION EJES LOCALES
 1535 FORMAT(/,I8,/,I8,/,I8)     
C*****************************************
C      WRITE(12,3015)I,NG1(I),NG2(I),NG3(I)
C 3015 FORMAT(/,'SECCION: ',I3,5X,'G1:',I5,3X,'G2:',I5,3X,'G3:',I5,/,/,/)
C*****************************************
C
C
      NNUR=NNUR+1
      INUDO(NNUR)=NG1(I)
      NNUR=NNUR+1
      INUDO(NNUR)=NG2(I)
      NNUR=NNUR+1
      INUDO(NNUR)=NG3(I)
C
C
  700 CONTINUE
C
C
      NNURR=NNUR
C
C*********************************
C      DO 544 I=1,NNUR            ! NUDOS DEL FICHERO .DAT ANTES DE PROCESARLOS
C      WRITE(12,3016)I,INUDO(I)
C  544 CONTINUE
C********************************
C
C
      DO 540 I=1,NNUR-1
C
      DO 541 K=I+1,NNUR
C
  547 CONTINUE
      IF(INUDO(I).EQ.INUDO(K))THEN
C
      DO 542 J=K,NNUR-1
      INUDO(J)=INUDO(J+1)
  542 CONTINUE
C
      NNUR=NNUR-1
C*********************************
C      DO 546 L=1,NNUR       
C      WRITE(12,3017)L,INUDO(L),K,I
C 3017 FORMAT(8X,I8,4X,I8,4X,'K=',I3,4X,'I=',I3)
C  546 CONTINUE
C********************************
      IF (K.GE.NNUR)GO TO 540 ! K PUEDE HACERSE MAYOR QUE NNUR (DA ERROR)
C
      GO TO 547  ! HAY QUE COMPARAR OTRA VEZ EL I CON EL NUEVO K YA QUE
      END IF     ! PODRIAN SER IGUALES. (ANTES DE CAMBIAR AL SIGUIENTE K)
C
C
  541 CONTINUE
  540 CONTINUE
C
      NNU=NNUR   ! NUMERO DE NUDOS DEL FICHERO .DAT DESPUES DE 
C                ! PROCESAR
C
C*********************************
C      DO 543 I=1,NNU    ! NUDOS DEL FICHERO .DAT DESPUES DE PROCESARLOS
C      WRITE(12,3016)I,INUDO(I)
C 3016 FORMAT(8X,I8,4X,I8)
C  543 CONTINUE
C********************************
C
C
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     DA VALORES A LAS VARIABLES PARA COMPROBAR SI EL
C     NUDO ESTA O NO ESTA EN EL MODELO
C
C
      DO 549 NN=1,NNU
C
      RCOOR(NN,1)=2745799.     ! 
      RCOOR(NN,2)=5789919.     ! VALORES CUALESQUIERA QUE NO EXISTAN
      RCOOR(NN,3)=9999999.     ! EN EL MODELO
C
  549 CONTINUE
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
C
C
C
C     LOCALIZA EL "ECHO" DEL BULK DATA
C     ================================
C
C
C
  500 READ(9,1000)ALFA1
 1000 FORMAT(50X,A11)
      IF(ALFA1.NE.'S O R T E D')GO TO 500
  505 READ(9,1005)ALINE1,ALINE2
 1005 FORMAT(30X,A4,4X,A48)
C
C
C   LECTURA DE LA CONECTIVIDAD DE LOS ELEMENTOS
C   ===========================================
C
C
      IF(ALINE1.EQ.'CBAR'.OR.ALINE1.EQ.'CROD'.OR.ALINE1.EQ.'CBEA')THEN
      NE=NE+1
      READ(ALINE2(1:48),1023)IELEM(NE),I,ICONEC(NE,1),ICONEC(NE,2)
 1023 FORMAT(BN,I8,BN,I8,BN,I8,BN,I8)
      ICONEC(NE,3)=0
      ICONEC(NE,4)=0
      END IF
C
      IF(ALINE1.EQ.'CQUA'.OR.ALINE1.EQ.'CSHE')THEN
      NE=NE+1
      READ(ALINE2(1:48),1022)IELEM(NE),I,ICONEC(NE,1),ICONEC(NE,2),
     +ICONEC(NE,3),ICONEC(NE,4)
 1022 FORMAT(BN,I8,BN,I8,BN,I8,BN,I8,BN,I8,BN,I8)
      END IF
C
      IF(ALINE1.EQ.'CTRI')THEN
      NE=NE+1
      READ(ALINE2(1:48),1024)IELEM(NE),I,ICONEC(NE,1),ICONEC(NE,2),
     +ICONEC(NE,3)
 1024 FORMAT(BN,I8,BN,I8,BN,I8,BN,I8,BN,I8)
      ICONEC(NE,4)=0
      END IF
C      
C      IF(ALINE1.EQ.'CELA')THEN
C      NE=NE+1
C      READ(ALINE2(1:48),*)IELEM(NE),I,ICONEC(NE,1),J,ICONEC(NE,2)
C      ICONEC(NE,3)=0
C      ICONEC(NE,4)=0
C      END IF
C
      IF(ALINE1.EQ.'CONR')THEN
      NE=NE+1
      READ(ALINE2(1:48),1026)IELEM(NE),ICONEC(NE,1),ICONEC(NE,2)
 1026 FORMAT(BN,I8,BN,I8,BN,I8)
      ICONEC(NE,3)=0
      ICONEC(NE,4)=0
      END IF
C
C     LECTURA DE LAS COORDENADAS DE LOS NUDOS
C     =======================================
C
C
      IF(ALINE1.EQ.'GRID')THEN  !!0000
      READ(ALINE2(1:48),1010)JNUDO,IEJ,RCOOR1,
     +RCOOR2,RCOOR3,JEJES
 1010 FORMAT(BN,I8,BN,I8,3F8.1,BN,I8)
C
      DO 545 NN=1,NNU
      IF(JNUDO.EQ.INUDO(NN))THEN  !!!!++
C
      NUDO(NN)=JNUDO          ! LA ORDENACION DE LOS NUDOS SE HACE 
      RCOOR(NN,1)=RCOOR1      ! TENIENDO EN CUENTA LA SELECCION DEL
      RCOOR(NN,2)=RCOOR2      ! FICHERO .DAT, Y NO LA DE LA TABLA
      RCOOR(NN,3)=RCOOR3      ! 'GRID' DEL 'ECHO' COMO SE HACIA ANTES.
      IEJES(NN)=JEJES         ! ESTO REDUCE EL TAMANO DE LAS VARIABLES
C
C
	IF(IEJ.NE.0.OR.JEJES.NE.0)WRITE(12,2001)JNUDO    ! ADVERTENCIA EJES LOCALES
 2001 FORMAT(/,12X,'ATENCION: EJES LOCALES EN NUDO:',I8) 
C
C
C
      IF(IEJ.EQ.8)THEN   ! CAMBIA LAS COORDENADAS DEL SISTEMA LOCAL 8
      RSX=RCOOR(NN,1)      ! (HELICE) DE LA NACELLE DERECHA AL SISTEMA
      RSY=RCOOR(NN,2)      ! GLOBAL
      RSZ=RCOOR(NN,3)
C
      RCOOR(NN,1)=RSX*0.99959996+RSY*0.01999799-RSZ*0.01999999+9419.5
      RCOOR(NN,2)=-RSX*0.02000199+RSY*0.99979994+4693.0
      RCOOR(NN,3)=RSX*0.01999599+RSY*0.00040004+RSZ*0.99979998+2951.3
C
      END IF
C
C
      IF(IEJ.EQ.9)THEN  ! SISTEMA LOCAL 9, NACELLE IZQUIERDA, A 
      RSX=RCOOR(NN,1)     ! SISTEMA GLOBAL
      RSY=RCOOR(NN,2)
      RSZ=RCOOR(NN,3)
C
      RCOOR(NN,1)=RSX*0.99959996-RSY*0.01999799-RSZ*0.01999999+9419.5
      RCOOR(NN,2)=RSX*0.02000199+RSY*0.99979994-4693.0
      RCOOR(NN,3)=RSX*0.01999599-RSY*0.00040004+RSZ*0.99979998+2951.3
C
      END IF
C
C
C***********************************
C      WRITE(12,2006)NN,NUDO(NN),IEJ,RCOOR1,RCOOR2,RCOOR3,JEJES
C 2006 FORMAT(4X,'NN=',I4,I8,I4,3F10.1,3X,I4)
C***********************************
C
      END IF  !!!!++
  545 CONTINUE
C
C
      END IF  !!0000
C
C
C     LOCALIZACION DEL FINAL DE LECTURA DE LOS DATOS DE ELEMENTOS
C     Y NUDOS
C     ===========================================================
C
C
      IF(ALINE1.EQ.'MAT1'.OR.ALINE1.EQ.'MAT2')GO TO 510
C
      GO TO 505
C
  510 CONTINUE
C
C
C******************************
C      WRITE(12,3080)FILEINF06,FILEINDAT,FILEINCAB,NNURR,
C     +N_MAX_NUDOS_DAT,NNU,N_MAX_NUDOS_DAT,NE,N_MAX_ELEMENTOS,
C     +NC,N_MAX_CASOS_F06
C 3080 FORMAT(/,/,/,/,7X,'FICHERO NASTRAN:   ',A50,/,7X,'FICHERO ',
C     +'DE DATOS:  ',A50,
C     +/,7X,'FICHERO CABECERA:  ',A50,/,/,
C     +7X,'NUDOS EN .DAT:            ',I4,7X,'LIMITE: ',I8,
C     +/,7X,'NUDOS DIFERENTES EN .DAT: ',I4,7X,'LIMITE: ',I8,
C     +/,7X,'ELEMENTOS PROCESADOS:    ',I5,7X,'LIMITE: ',I8,
C     +/,7X 'CASOS CARGA F06:         ',I5,7X,'LIMITE: ',I8,/,/)
C******************************
C
C
C
C
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     ESCRIBE EL NUMERO DE NUDO DEL .DAT QUE NO ESTA EN EL MODELO
C
      DO 551 NJJ=1,NNU
C
      IF(RCOOR(NJJ,1).EQ.2745799..AND.RCOOR(NJJ,2).EQ.5789919.
     +.AND.RCOOR(NJJ,3).EQ.9999999.)THEN
      WRITE(12,3083)INUDO(NJJ)
 3083 FORMAT(/,7X,'EL NUDO ',I8,' NO EXISTE EN EL MODELO',/)
      END IF
C
  551 CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
C
C
C ***************************************************************
C      ESCRIBE CONECTIVIDAD Y COORDENADAS NUDOS PARA COMPROBACION
C
C
C      DO 600 I=1,NE
C      WRITE(12,2000)IELEM(I),ICONEC(I,1),ICONEC(I,2),ICONEC(I,3),
C     +ICONEC(I,4)
C 2000 FORMAT(5X,5I10)
C  600 CONTINUE
C
C      DO 605 J=1,NNU
C      WRITE(12,2005)NUDO(J),RCOOR(J,1),RCOOR(J,2),RCOOR(J,3)
C 2005 FORMAT(5X,I5,5X,3F10.1)
C  605 CONTINUE
C
C****************************************************************
C
C
C
C
C
C
C      EN CADA SECCION, PARA CADA NUDO, IDENTIFICA LOS ELEMENTOS CONECTADOS
C      A LA VEZ A DICHO NUDO Y A LOS NUDOS DEL OTRO LADO
C      ====================================================================
C
C
C 
      DO 720 K=1,NUMSEC
C
      DO 720 L=1,NUMNUDA(K)
C
      N1=NNUDA(K,L)
      NEAUX2=0
C
      DO 721 M=1,NUMNUDB(K)
C
      N2=NNUDB(K,M)
C
      DO 721 I=1,NE
C
      DO 725 J=1,4
C
      IF(ICONEC(I,J).EQ.0)GO TO 725
      IF(ICONEC(I,J).EQ.N1)NBIT2=1
      IF(ICONEC(I,J).EQ.N2)NBIT3=1
C
  725 CONTINUE
C
      IF(NBIT2.EQ.1.AND.NBIT3.EQ.1)THEN
      NEAUX2=NEAUX2+1
C
C*******************************************
C      WRITE(12,3025)K,L,NEAUX2,IELEM(I)
C 3025 FORMAT(2X,'SECCION:',I3,4X,'ORDEN NUDO:',I5,4X,'NEAUX2:',I3,4X,
C     +'NE:',I5)
C*******************************************
C
      IELSEL(K,L,NEAUX2)=IELEM(I)  ! ELEMENTOS CONECTADOS A LOS DOS NUDOS
C
C
      IF(NEAUX2.EQ.1)GO TO 731
      MM=NEAUX2-1
C                       ! EVITA QUE SE ASIGNE DOS VECES EL MISMO ELEMENTO A
      DO 730 II=1,MM                                 ! UN NUDO
      IF(IELSEL(K,L,NEAUX2).EQ.IELSEL(K,L,II))THEN
      IELSEL(K,L,NEAUX2)=0
      NBIT5=1
      END IF
  730 CONTINUE
  731 CONTINUE
C 
      IF(NBIT5.EQ.1)NEAUX2=NEAUX2-1
      NBIT5=0
C
      END IF
C
C
      NBIT2=0
      NBIT3=0
C
  721 CONTINUE
C*****************************************
C      DO 900 JJ=1,NEAUX2
C      WRITE(12,3020)K,NNUDA(K,L),IELSEL(K,L,JJ)
C 3020 FORMAT(/,2X,'SECCION:',I3,2X,'NUDO:',I8,3X,'ELEMENTO:',I8)
C  900 CONTINUE
C*****************************************
C
  720 CONTINUE
C
C
C
C      PARA CADA SECCION CALCULA LOS COSENOS DIRECTORES EN LAS DOS
C      DIRECCIONES (CORTADURA Y CARGA AXIAL)
C      ===========================================================
C
C
C
C
      DO 735 I=1,NUMSEC
C
      DO 740 J=1,NNU
C
      IF(NUDO(J).EQ.NG1(I))NN1=J   ! A CADA NUDO LE ASIGNA EL NUMERO
      IF(NUDO(J).EQ.NG2(I))NN2=J   ! CORRELATIVO QUE LE CORRESPONDE
      IF(NUDO(J).EQ.NG3(I))NN3=J
C
  740 CONTINUE
C
      RX2=RCOOR(NN2,1)-RCOOR(NN1,1)
      RY2=RCOOR(NN2,2)-RCOOR(NN1,2)
      RZ2=RCOOR(NN2,3)-RCOOR(NN1,3)
      RRT=(RX2**2+RY2**2+RZ2**2)**0.5    ! MODULO VECTOR DIRECCION 'X'
C
      RX3=RCOOR(NN3,1)-RCOOR(NN1,1)
      RY3=RCOOR(NN3,2)-RCOOR(NN1,2)
      RZ3=RCOOR(NN3,3)-RCOOR(NN1,3)
C
      RXZ=RY2*RZ3-RY3*RZ2
      RYZ=RZ2*RX3-RZ3*RX2  ! PRODUCTO VECTORIAL G2 X G3. (EJE LOCAL  Z)
      RZZ=RX2*RY3-RX3*RY2
      RRZ=(RXZ**2+RYZ**2+RZZ**2)**0.5    ! MODULO VECTOR DIRECCION 'Z'
C
      RXY=RYZ*RZ2-RY2*RZZ
      RYY=RZZ*RX2-RZ2*RXZ  ! PRODUCTO VECTORIAL Z X G2. (EJE LOCAL  Y)
      RZY=RXZ*RY2-RX2*RYZ
      RRL=(RXY**2+RYY**2+RZY**2)**0.5    ! MODULO VECTOR DIRECCION 'Y'
C
      RLCOSALF(I)=RXY/RRL
      RLCOSBET(I)=RYY/RRL  ! COSENOS DIRECTORES DE LA DIRECCION 'Y'
      RLCOSGAM(I)=RZY/RRL  ! DEL SISTEMA GLOBAL
C
      RTCOSALF(I)=RX2/RRT
      RTCOSBET(I)=RY2/RRT  ! COSENOS DIRECTORES DE LA DIRECCION 'X'
      RTCOSGAM(I)=RZ2/RRT  ! DEL SISTEMA GLOBAL
C
      RZCOSALF(I)=RXZ/RRZ  
      RZCOSBET(I)=RYZ/RRZ  ! COSENOS DIRECTORES DE LA DIRECCION Z LOCAL
      RZCOSGAM(I)=RZZ/RRZ
C
C*********************************************
C      WRITE(12,3034)I,RX2,RY2,RZ2,RX3,RY3,RZ3,RXZ,RYZ,RZZ,RXY,RYY,RZY
C 3034 FORMAT('SECCION:',I3,/,8X,3F10.1,/,8X,3F10.1,/,8X,3F10.1,
C     +/,8X,3F10.1,/)   
C*********************************************
C******************************************
C      WRITE(12,3035)I,RLCOSALF(I),RLCOSBET(I),RLCOSGAM(I),
C     +RTCOSALF(I),RTCOSBET(I),RTCOSGAM(I),RZCOSALF(I),RZCOSBET(I),
C     +RZCOSGAM(I)
C 3035 FORMAT(/,/,2X,'SECCION:',I3,3X,'COSALF(L):',F7.3,4X,'COSBET(L):'
C     +,F7.3,4X,'COSGAM(L):',F7.3,/,16X,'COSALF(T):',F7.3,4X,'COSBET(T):
C     +',F7.3,4X,'COSGAM(T):',F7.3,/,16X,'COSALF(Z):',F7.3,4X,'COSBET(Z)
C     +:',F7.3,4X,'COSGAM(Z):',F7.3,/)
C******************************************
  735 CONTINUE
C
C
C
C
C
C
C      CALCULA LAS DISTANCIAS DESDE CADA NUDO DE LA SECCION HASTA EL 
C      NUDO ORIGEN DE LA MISMA "NG1".
C      LA SECCION DEBE SER PLANA O PRACTICAMENTE PLANA
C      =============================================================
C
C
C
      DO 741 I=1,NUMSEC
C
      DO 746 J=1,NNU
C
C
C
C
C
CCCCCC      IF(NUDO(J).EQ.NG1(I))NREF=J
C
C     NUDO DE REFERENCIA EL PRIMERO DE LA SECCION, NO TIENE
C     POR QUE SER EL NG1
C
      IF(NUDO(J).EQ.NNUDA(I,1))NREF=J
C
C
C
C
C
  746 CONTINUE
C
      DO 741 K=1,NUMNUDA(I)
C
      DO 741 L=1,NNU
C
      IF(NUDO(L).EQ.NNUDA(I,K))THEN
C
C      RDISTANCIA(I,K)=((RCOOR(L,1)-RCOOR(NREF,1))**2+(RCOOR(L,2)-
C     +RCOOR(NREF,2))**2+(RCOOR(L,3)-RCOOR(NREF,3))**2)**0.5
C
C      RDISTANCIA(I,K)=(RCOOR(L,1)-RCOOR(NREF,1))*RTCOSALF(I)+(RCOOR(L,2)
C     +-RCOOR(NREF,2))*RTCOSBET(I)+(RCOOR(L,3)-RCOOR(NREF,3))*RTCOSGAM(I)
C
C
C
C     DISTANCIAS DE CADA NUDO AL DE REFERENCIA DEGÚN LOS TRES EJES DEL
C     SISTEMA DE REFERENCIA
C
C     
      RTDIST(I,K)=(RCOOR(L,1)-RCOOR(NREF,1))*RTCOSALF(I)+(RCOOR(L,2)
     +-RCOOR(NREF,2))*RTCOSBET(I)+(RCOOR(L,3)-RCOOR(NREF,3))*RTCOSGAM(I)
C 
C     
      RLDISL(I,K)=(RCOOR(L,1)-RCOOR(NREF,1))*RLCOSALF(I)+(RCOOR(L,2)
     +-RCOOR(NREF,2))*RLCOSBET(I)+(RCOOR(L,3)-RCOOR(NREF,3))*RLCOSGAM(I)
C
C     
      RZDISZ(I,K)=(RCOOR(L,1)-RCOOR(NREF,1))*RZCOSALF(I)+(RCOOR(L,2)
     +-RCOOR(NREF,2))*RZCOSBET(I)+(RCOOR(L,3)-RCOOR(NREF,3))*RZCOSGAM(I)
C     
C     
C
C
C***************************************
C      WRITE(12,3030)I,NUDO(NREF),NUDO(L),RDISTANCIA(I,K)
C 3030 FORMAT(2X,'SECCION:',I3,3X,'G1:',I8,3X,'NUDO:',I8,3X,'DIS:',
C     +F10.1)
C***************************************
      END IF
C
  741 CONTINUE
C
C
C
C
C
C
C     LOCALIZA EL COMIENZO DEL EQUILIBRIO DE FUERZAS EN
C     LOS NUDOS
C     =================================================
C
C
C
  515 READ(10,1015)ALFA1 
 1015 FORMAT(76X,A11)
      IF(ALFA1.NE.'B A L A N C')GO TO 515
      BACKSPACE 10
      BACKSPACE 10
      BACKSPACE 10
      BACKSPACE 10
      BACKSPACE 10
C
C
C     IDENTIFICA EL CASO DE CARGA Y FINAL DEL FICHERO
C     ================================================
C
C
  520 READ(10,1020)ACASO,ALFA2,ALFA3,ALFA4
 1020 FORMAT(5X,A40,A8,56X,A3,A14)
C
C
      IF(ALFA3.EQ.'SUB')THEN
C
      READ(ALFA4(1:6),1064)ABIT
 1064 FORMAT(5X,A1)
C
      IF(ABIT.EQ.'=')READ(ALFA4(1:14),1065)ICASE
      IF(ABIT.NE.'=')READ(ALFA4(1:14),1066)ICASE
C
 1065 FORMAT(6X,BN,I8)
 1066 FORMAT(5X,BN,I8)
C
C
C
C*************************************************
C      WRITE(12,2045)ICASE
C 2045 FORMAT(/,2X,'ICASE:',I4) 
C      WRITE(12,1020)ACASO,ALFA2,ALFA3
C*************************************************
      END IF
C
      IF(ALFA3.NE.'SUB')GO TO 520
      IICASE(NC)=ICASE
      CASO(NC)=ACASO
C
  518 READ(10,1025)
 1025 FORMAT(/)
C
C
C
C
C     LEE LAS FUERZAS SOBRE LOS NUDOS
C     ===============================
C
C
C
  525 READ(10,1030)ALINE3,ALINE4,ALINE5
 1030 FORMAT(1X,A28,A4,8X,A90)
C
      READ(ALINE5(55:58),1036)ALFA5   ! LOCALIZA EL FINAL DE CADA TABLA
 1036 FORMAT(A4)                      !   'MSC/' o 'MSC.' o 'MSC '
C
C********************************************
C      WRITE(12,1030)ALINE3,ALINE4,ALINE5
C********************************************
C
      IF(ALINE4.EQ.'BAR '.OR.ALINE4.EQ.'ROD '.OR.ALINE4.EQ.'BEAM'.OR.
     +ALINE4.EQ.'QUAD'.OR.ALINE4.EQ.'SHEA'.OR.ALINE4.EQ.'TRIA'
     +.OR.ALINE4.EQ.'CONR')THEN
      NEAUX=NEAUX+1
      READ(ALINE3(1:28),*)NUDO2,IELEM2
C
C**************************************
C      WRITE(12,2050)NNU
C 2050 FORMAT(2X,'NNU= ',I10)
C**************************************
C
      NBIT7=0
C
      DO 530 I=1,NNU           ! EVITA QUE SE LEAN FUERZAS PARA NUDOS
      IF(NUDO2.EQ.NUDO(I))THEN ! QUE NO ESTAN EN EL FICHERO  .DAT
      NNAUX=I
      NBIT7=1
      END IF
  530 CONTINUE
C
      IF(NBIT7.NE.1)GO TO 525
C
      ICONNUD(NNAUX,NEAUX)=IELEM2
C
C*****************************************************************
C      WRITE(12,2022)NUDO2,IELEM2,NNAUX,NEAUX,ICONNUD(NNAUX,NEAUX)
C 2022 FORMAT(5X,I9,1X,I9,6X,3I8)
C*****************************************************************
C
C
      READ(ALINE5(1:90),1035)RFUERZA(NNAUX,NEAUX,1),
     +RFUERZA(NNAUX,NEAUX,2),RFUERZA(NNAUX,NEAUX,3),
     +RFUERZA(NNAUX,NEAUX,4),RFUERZA(NNAUX,NEAUX,5),
     +RFUERZA(NNAUX,NEAUX,6)
 1035 FORMAT(6F15.1)
C
C
C
      IF(IEJES(NNAUX).EQ.1)THEN    ! SISTEMA LOCAL '1', RAMPA  
      RSX=RFUERZA(NNAUX,NEAUX,1)   ! AVION C-255 Y CN-235
      RSY=RFUERZA(NNAUX,NEAUX,2)
      RSZ=RFUERZA(NNAUX,NEAUX,3)
      RBX=RFUERZA(NNAUX,NEAUX,4)
      RBY=RFUERZA(NNAUX,NEAUX,5)
      RBZ=RFUERZA(NNAUX,NEAUX,6)
C
      RFUERZA(NNAUX,NEAUX,1)=RSX*0.9389341839-RSZ*0.3440967863
      RFUERZA(NNAUX,NEAUX,2)=RSY
      RFUERZA(NNAUX,NEAUX,3)=RSX*0.3440967863+RSZ*0.9389341839
      RFUERZA(NNAUX,NEAUX,4)=RBX*0.9389341839-RBZ*0.3440967863
      RFUERZA(NNAUX,NEAUX,5)=RBY
      RFUERZA(NNAUX,NEAUX,6)=RBX*0.3440967863+RBZ*0.9389341839
C
      END IF
C
C
      IF(IEJES(NNAUX).EQ.8)THEN  ! SISTEMA LOCAL '8', NACELLE DERECHA DEL
      RSX=RFUERZA(NNAUX,NEAUX,1) ! AVION C-3000
      RSY=RFUERZA(NNAUX,NEAUX,2)
      RSZ=RFUERZA(NNAUX,NEAUX,3)
      RBX=RFUERZA(NNAUX,NEAUX,4)
      RBY=RFUERZA(NNAUX,NEAUX,5)
      RBZ=RFUERZA(NNAUX,NEAUX,6)
C
      RFUERZA(NNAUX,NEAUX,1)=RSX*0.99959996+RSY*0.01999799-RSZ
     +*0.01999999
      RFUERZA(NNAUX,NEAUX,2)=-RSX*0.02000199+RSY*0.99979994
      RFUERZA(NNAUX,NEAUX,3)=RSX*0.01999599+RSY*0.00040004+RSZ
     +*0.99979998
      RFUERZA(NNAUX,NEAUX,4)=RBX*0.99959996+RBY*0.01999799-RBZ
     +*0.01999999
      RFUERZA(NNAUX,NEAUX,5)=-RBX*0.02000199+RBY*0.99979994
      RFUERZA(NNAUX,NEAUX,6)=RBX*0.01999599+RBY*0.00040004+RBZ
     +*0.99979998
C
      END IF
C
C
C
      IF(IEJES(NNAUX).EQ.9)THEN  ! SISTEMA LOCAL '9', NACELLE IZQUIERDA
      RSX=RFUERZA(NNAUX,NEAUX,1) ! DEL AVION C-3000
      RSY=RFUERZA(NNAUX,NEAUX,2)
      RSZ=RFUERZA(NNAUX,NEAUX,3)
      RBX=RFUERZA(NNAUX,NEAUX,4)
      RBY=RFUERZA(NNAUX,NEAUX,5)
      RBZ=RFUERZA(NNAUX,NEAUX,6)
C
C
      RFUERZA(NNAUX,NEAUX,1)=RSX*0.99959996-RSY*0.01999799-RSZ
     +*0.01999999
      RFUERZA(NNAUX,NEAUX,2)=RSX*0.02000199+RSY*0.99979994
      RFUERZA(NNAUX,NEAUX,3)=RSX*0.01999599-RSY*0.00040004+RSZ
     +*0.99979998
      RFUERZA(NNAUX,NEAUX,4)=RBX*0.99959996-RBY*0.01999799-RBZ
     +*0.01999999
      RFUERZA(NNAUX,NEAUX,5)=RBX*0.02000199+RBY*0.99979994
      RFUERZA(NNAUX,NEAUX,6)=RBX*0.01999599-RBY*0.00040004+RBZ
     +*0.99979998
C
      END IF
C
C
C
      END IF
C
      IF(ALFA5.EQ.'MSC/'.OR.ALFA5.EQ.'MSC.'.OR.ALFA5.EQ.'MSC ')THEN
C
C
C
C
C
  519 READ(10,1020)ACASO,ALFA2,ALFA3,ALFA4
C
      IF(ALFA2.EQ.'* END OF')GO TO 580
C
      IF(ALFA3.EQ.'SUB')THEN
C
      READ(ALFA4(1:6),1064)ABIT
C
      IF(ABIT.EQ.'=')READ(ALFA4(1:14),1065)ICASE
      IF(ABIT.NE.'=')READ(ALFA4(1:14),1066)ICASE
C
C
C*************************************************
C      WRITE(12,2045)ICASE
C      WRITE(12,1020)ACASO,ALFA2,ALFA3
C*************************************************
      END IF
C
      IF(ALFA3.NE.'SUB')GO TO 519
C
C
C*****************************************************
C      WRITE(12,3045)NC,CASO(NC),ACASO,IICASE(NC),ICASE
C 3045 FORMAT(2X,'NC',I4,2A40,'IICASE(NC),ICASE',2I5)
C*****************************************************
C
C
C
C
  580 IF(CASO(NC).NE.ACASO.OR.IICASE(NC).NE.ICASE
     +.OR.ALFA2.EQ.'* END OF')THEN
C
C
C
C
C     EN CADA SECCION CALCULA LAS FUERZAS SOBRE CADA NUDO Y LAS
C     TRASLADA HASTA EL NUDO ORIGEN "NG1"
C     =========================================================
C
C
      IF(NBIT8.EQ.1)THEN   ! +++  LEE SOLO LAS TABLAS 'B A L A N C E'
      NBIT8=0
C
C
C
C
      DO 747 I=1,NUMSEC
C
C*********************************************
C      WRITE(12,3050)NUMSEC,I,NUMCASOS(I)
C 3050 FORMAT(2X,'NUMSEC:',I4,2X,'I:',I3,2X,'NUMCASOS(I):',I3)
C*********************************************
C
C
      IF(INUMCASOS(I).LE.0)THEN    ! SE HA PUESTO 0 EN EL NÚMERO DE CASOS DE LA SECCION
      J=NC                         ! CALCULA TODOS LOS CASOS SI EL NUMERO ES NEGATIVO
      GO TO 776
      END IF
C
      DO 775 JJ=1,NUMCASOS(I)
C
      IF(NCAS(I,JJ).EQ.NC)THEN
      NBIT6=1
      J=JJ
      END IF
C
C**************************************
C      WRITE(12,3055)I,JJ,NCAS(I,JJ),NBIT6
C 3055 FORMAT(2X,'I:',I3,2X,'JJ:',I3,2X,'NCAS(I,JJ):',I3,2X,'NBIT6:',I2)
C**************************************
C
C
  775 CONTINUE
C
      IF(NBIT6.NE.1)GO TO 765
C
      NBIT6=0
C
C
C
  776 CONTINUE
C
C
C
C
C
CCCC      NCASO=NCAS(I,J)
      RLT(I,J)=0.
      RZT(I,J)=0.
      RTT(I,J)=0.
      RMOMENTL(I,J)=0.
      RMOMENTT(I,J)=0.
      RMOMENTZ(I,J)=0.      
C
C
      DO 745 K=1,NUMNUDA(I)   ! PARA CADA NUDO DE LA SECCION
C
      RL=0.
      RT=0.
      RZ=0.       
      RMOMEL=0.
      RMOMET=0.
      RMOMEZ=0.
C
      DO 760 KK=1,NNU             ! TODOS LOS NUDOS DEL MODELO
      IF(NUDO(KK).EQ.NNUDA(I,K))NUDOG=KK
  760 CONTINUE
C
      RFX=0.
      RFY=0.
      RFZ=0.
      RMX=0.
      RMY=0.
      RMZ=0.
C
      DO 750 L=1,N_MAX_ELEM_1NUDO  ! PARA TODOS LOS ELEMENTOS CONECTADOS AL NUDO
C                                  ! "IELSEL"  (MAXIMO 56)
      IF(IELSEL(I,K,L).EQ.0)GO TO 751
C
      NE2=0
C
      DO 755 M=1, N_MAX_ELEM_1NUDO  ! PARA TODOS LOS ELEMENTOS CONECTADOS AL NUDO
C                                   ! "RFUERZA"  
      IF(ICONNUD(NUDOG,M).EQ.0)GO TO 755
      IF(ICONNUD(NUDOG,M).EQ.IELSEL(I,K,L))THEN
      NE2=M
      END IF
C
  755 CONTINUE
C
      IF(NE2.EQ.0)GO TO 750   ! SE SALTA LOS CALCULOS SI NO EXISTE EL
C                             ! ELEMENTO (CONEXION FICHEROS .F06 PARA
C                             ! CASOS FAIL-SAFE)
C
      RFX=RFUERZA(NUDOG,NE2,1)
      RFY=RFUERZA(NUDOG,NE2,2)
      RFZ=RFUERZA(NUDOG,NE2,3)
      RMX=RFUERZA(NUDOG,NE2,4)
      RMY=RFUERZA(NUDOG,NE2,5)
      RMZ=RFUERZA(NUDOG,NE2,6)
C 
      RL=RFX*RLCOSALF(I)+RFY*RLCOSBET(I)+
     +RFZ*RLCOSGAM(I)+RL
C 
      RT=RFX*RTCOSALF(I)+RFY*RTCOSBET(I)+
     +RFZ*RTCOSGAM(I)+RT
C
C
      RZ=RFX*RZCOSALF(I)+RFY*RZCOSBET(I)+
     +RFZ*RZCOSGAM(I)+RZ
CC
C      RMOMEN=(RFX*RLCOSALF(I)+RFY*RLCOSBET(I)+RFZ*
C     +RLCOSGAM(I))*RDISTANCIA(I,K)+RMOMEN+
C     +RMX*RZCOSALF(I)+RMY*RZCOSBET(I)+RMZ*RZCOSGAM(I)
CC
C
      RMOMEZ=(RFX*RLCOSALF(I)+RFY*RLCOSBET(I)+RFZ*
     +RLCOSGAM(I))*RTDIST(I,K)-
     +(RFX*RTCOSALF(I)+RFY*RTCOSBET(I)+RFZ*
     +RTCOSGAM(I))*RLDISL(I,K)+RMOMEZ+
     +RMX*RZCOSALF(I)+RMY*RZCOSBET(I)+RMZ*RZCOSGAM(I)
C
      RMOMET=(RFX*RZCOSALF(I)+RFY*RZCOSBET(I)+RFZ*
     +RZCOSGAM(I))*RLDISL(I,K)-
     +(RFX*RLCOSALF(I)+RFY*RLCOSBET(I)+RFZ*
     +RLCOSGAM(I))*RZDISZ(I,K)+RMOMET+
     +RMX*RTCOSALF(I)+RMY*RTCOSBET(I)+RMZ*RTCOSGAM(I)
C
      RMOMEL=(RFX*RTCOSALF(I)+RFY*RTCOSBET(I)+RFZ*
     +RTCOSGAM(I))*RZDISZ(I,K)-
     +(RFX*RZCOSALF(I)+RFY*RZCOSBET(I)+RFZ*
     +RZCOSGAM(I))*RTDIST(I,K)+RMOMEL+
     +RMX*RLCOSALF(I)+RMY*RLCOSBET(I)+RMZ*RLCOSGAM(I)
C
C
C***********************************************
C      WRITE(12,3039)NNUDA(I,K),IELSEL(I,K,L),RFX,RFY,RFZ,RMX,RMY,
C     +RMZ,RDISTANCIA(I,K),RL,RT,RMOMEN
C 3039 FORMAT(/,2X,'NUDO:',I8,2X,'ELE:',I8,2X,3F10.1,3F14.1,/,
C     +2X,'DIST:',F8.1,4X,'RL,RT,RMOMEN:',2F10.1,F14.1,/)
C***********************************************
C
  750 CONTINUE
  751 CONTINUE
C
C***************************************************
C      WRITE(12,3040)I,NNUDA(I,K),NCAS(I,J),RL,RT,I,K,RDISTANCIA(I,K),
C     +RMOMEN
C 3040 FORMAT(2X,'SECCION: ',I3,6X,'NUDO:',I8,6X,'CASO: ',I3,/,3X,
C     +'RL=',F10.1,5X,'RT=',F10.1,5X,2I3,1X,'DIS:',F10.1,5X,'M=',
C     +F15.1,/,/)
C***************************************************
C
       RLT(I,J)=RL+RLT(I,J)
C      RLT(I,J)=RFX*RLCOSALF(I)+RFY*RLCOSBET(I)+
C     +RFZ*RLCOSGAM(I)+RLT(I,J)
C
       RTT(I,J)=RT+RTT(I,J)
C      RTT(I,J)=RFX*RTCOSALF(I)+RFY*RTCOSBET(I)+
C     +RFZ*RTCOSGAM(I)+RTT(I,J)
C
       RZT(I,J)=RZ+RZT(I,J)
C
C      RMOMENTO(I,J)=RMOMENTO(I,J)+RMOMEN  
C
      RMOMENTL(I,J)=RMOMENTL(I,J)+RMOMEL  
      RMOMENTT(I,J)=RMOMENTT(I,J)+RMOMET  
      RMOMENTZ(I,J)=RMOMENTZ(I,J)+RMOMEZ  
C
  745 CONTINUE
C
C***************************************************
C      WRITE(12,3041)I,NCAS(I,J),RLT(I,J),RTT(I,J),
C     +RMOMENTO(I,J)
C 3041 FORMAT(15X,'SECCION: ',I3,6X,'CASO: ',I3,'  **********',/,18X,
C     +'RLT=',F10.1,5X,'RTT=',F10.1,5X,'M=',F15.1,/,/)
C***************************************************
C
C
C
C
C
  765 CONTINUE
C
  747 CONTINUE
C
C
C
      END IF  ! +++
C
C   PONE EN CERO LOS VALORES DE `RFUERZA' E `ICONNUD' ANTES DE LEER
C   EL SIGUIENTE CASO.  ( EVITA ERRORES EN FAIL- SAFE )
C
C
      DO 556 IRF=1,N_MAX_NUDOS_DAT          ! CAMBIAR LAS DIMENSIONES DE ESTAS
      DO 556 JRF=1,N_MAX_ELEM_1NUDO         ! VARIABLES DE ACUERDO CON LA TARJETA DIMENSION
C                                           ! HAY QUE CAMBIAR TAMBIEN LOS CONTADORES DE LOS
      ICONNUD(IRF,JRF)=0 ! 'DO'  NUMEROS 750 Y 755
C
      DO 556 KRF=1,6
      RFUERZA(IRF,JRF,KRF)=0.
  556 CONTINUE
C  
C
C
C
      READ(10,1021)ALFA1             ! EVITA QUE SE LEA OTRO TIPO DE
 1021 FORMAT(/,76X,A11)              ! INFORMACION DIFERENTE DE LA
      IF(ALFA1.EQ.'B A L A N C')THEN ! DEL   'GPFORCE'  ***
C
C
      NBIT8=1
C
C
C
      IF(ALFA2.NE.'* END OF')THEN
      NC=NC+1                        ! CONTADOR DE CASOS DE CARGA
      CASO(NC)=ACASO
      IICASE(NC)=ICASE
      NEAUX=0
      END IF
C
      END IF                         ! ***
C
      IF(ALFA2.EQ.'* END OF')GO TO 770
C
C
      END IF
C
      GO TO 518
C
      END IF
C
C
C
      IF(ALINE4.EQ.'*TOT')NEAUX=0
C
C
      GOTO 525
C
  770 CONTINUE
C
C
C
C
C******************************
      WRITE(12,3080)FILEINF06,FILEINDAT,FILEINCAB,NNURR,
     +N_MAX_NUDOS_DAT,NNU,N_MAX_NUDOS_DAT,NE,N_MAX_ELEMENTOS,
     +NC,N_MAX_CASOS_F06
 3080 FORMAT(/,/,/,/,7X,'FICHERO NASTRAN:   ',A50,/,7X,'FICHERO ',
     +'DE DATOS:  ',A50,
     +/,7X,'FICHERO CABECERA:  ',A50,/,/,
     +7X,'NUDOS EN .DAT:            ',I4,7X,'LIMITE: ',I8,
     +/,7X,'NUDOS DIFERENTES EN .DAT: ',I4,7X,'LIMITE: ',I8,
     +/,7X,'ELEMENTOS PROCESADOS:    ',I5,7X,'LIMITE: ',I8,
     +/,7X 'CASOS CARGA EN F06:      ',I5,7X,'LIMITE: ',I8,/,/)
C******************************
C
C
C
C
C
C
C     ESCRITURA DE RESULTADOS
C     =======================
C
C
      WRITE(12,1501)ATITULO
 1501 FORMAT(/,/,2X,'TITULO: ',A70,/,2X,'=======',/)
C
C
C
      DO 800 I=1,NUMSEC
C
C
 	IF(ROFSET(I).NE.0) GO TO 807     ! EN 807 SE CALCULAN MAXIMOS Y MINIMOS
C
C
C
C      WRITE(12,3060)I,NNUDA(I,1),NG1(I),NG2(I),NG3(I)
C
      WRITE(12,3060)I,NNUDA(I,1),NG1(I),NG2(I),NG3(I),ROFSET(I)
C
C
 3060 FORMAT(/,/,/,/,8X,'SECCION:',I3,'  (',I8,')',
     +2X,'N1:',I8,3X,'N2:',I8,3X,
     +'N3:',I8,4X,'OFSET:',F8.3,
     +/,8X,'============',/,/,3X,'CASO',4X,'   MZ   ',
     +5X,'   FX   ',8X,'FY',20X,'MX',11X,'FZ',11X,'MY',/)
C
C
      IF(NUMCASOS(I).EQ.0)THEN    ! SI SE PONE 0 EN EL NUMERO DE CASOS DE UNA SECCION
      DO 809 JJ=1,NC		     
      J=JJ
C
C
C     WRITE(12,3065)J,RTT(I,J),RLT(I,J),RMOMENTZ(I,J),RZT(I,J),
C    +RMOMENTT(I,J),RMOMENTL(I,J)
C
      WRITE(12,3065)J,RMOMENTZ(I,J),RTT(I,J),RLT(I,J),
     +RMOMENTT(I,J),RZT(I,J),RMOMENTL(I,J)
C
C
  809 CONTINUE
      GO TO 703
      END IF
C
C
	IF(INUMCASOS(I).LT.0)THEN      !NO IMPRIME LOS CASOS QUE SE QUITAN
      DO 907 JJ=1,NC		     
      J=JJ
C
	DO 903 K=1,NUMCASOS(I)
	IF(NCAS(I,K).EQ.IICASE(J))GO TO 904
  903 CONTINUE
C
C      WRITE(12,3065)J,RTT(I,J),RLT(I,J),RMOMENTZ(I,J),RZT(I,J),
C     +RMOMENTT(I,J),RMOMENTL(I,J)
C
      WRITE(12,3065)J,RMOMENTZ(I,J),RTT(I,J),RLT(I,J),
     +RMOMENTT(I,J),RZT(I,J),RMOMENTL(I,J)
C
C
  904 CONTINUE

  907 CONTINUE
      GO TO 703
      END IF
C
C
C
C
      DO 704 JJ=1,NUMCASOS(I)
      J=JJ
C
      DO 701 K=J+1,NUMCASOS(I)       ! EVITA QUE SALGA '0.' CUANDO HAY CASOS
      IF(NCAS(I,K).EQ.NCAS(I,J))THEN ! DE CARGA REPETIDOS EN UNA MISMA
      J=K                            ! SECCION DEL FICHERO  .DAT
      END IF
  701 CONTINUE
C
      NCASO=NCAS(I,J)
C
C      WRITE(12,3065)NCASO,RLT(I,J),RTT(I,J),RMOMENTO(I,J)
C 3065 FORMAT(8X,I3,5X,F16.2,4X,F16.2,4X,F16.2)
C
C      WRITE(12,3065)NCASO,RTT(I,J),RLT(I,J),RMOMENTZ(I,J),RZT(I,J),
C     +RMOMENTT(I,J),RMOMENTL(I,J)
C
C
      WRITE(12,3065)NCASO,RMOMENTZ(I,J),RTT(I,J),RLT(I,J),
     +RMOMENTT(I,J),RZT(I,J),RMOMENTL(I,J)
C
 3065 FORMAT(2X,I4,1X,F12.1,1X,F12.1,1X,F12.1,10X,F12.1,1X,F12.1,
     +1X,F12.1)
C
C
C
  704 CONTINUE
C
  703 CONTINUE
	GO TO 808
C
C
  807 CONTINUE
C
C
C    ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
C
C
C
C	CALCULA MAXIMOS Y MINIMOS EN OFSET Y LOS ESCRIBE
C
C
C
      WRITE(12,3061)I,NNUDA(I,1),NG1(I),NG2(I),NG3(I),ROFSET(I)
C
C 3061 FORMAT(/,/,/,/,8X,'SECCION:',I3,'  (',I8,')',
C     +2X,'N1:',I8,3X,'N2:',I8,3X,
C     +'N3:',I8,4X,'OFSET:',F8.3,
C     +/,8X,'============',/,/,
C     +26X,'MF (Z) ',6X,'AX (X)',6X,'V (Y',
C     +')',6X,'V (Y) ',6X,'CASO',10X,'FY',10X,'FZ',10X,'MY',10X,'MZ',/)
C
C
C
 3061 FORMAT(/,/,/,/,8X,'SECCION:',I3,'  (',I8,')',
     +2X,'N1:',I8,3X,'N2:',I8,3X,
     +'N3:',I8,4X,'OFSET:',F8.3,
     +/,8X,'============',/,/,
     +18X,'CASO',9X,'MZ',10X,'FX',9X,'(FY)',
     +19X,'FY',10X,'MX',10X,'FZ',10X,'MY',/)
C
C
C
C
      IF(NUMCASOS(I).EQ.0)THEN    ! SI SE PONE 0 EN EL NUMERO DE CASOS DE UNA SECCION
C
      RFLEMAX=-1.0E35  ! MAXIMA FLEXION, TORSION Y FUERZA AXIAL
      RFLEMIN=1.0E35
      RTORMAX=-1.0E35
      RAXMAX=-1.0E35
      RAXMIN=1.0E35
      RCORMAX=-1.0E35
C
      ICAFLE=0    ! CASOS DE CARGA PARA LOS VALORES MAXIMOS
      IFLMIN=0
      ICATOR=0
      IAXMA=0
      IAXMI=0
      ICACOR=0
C
C
C
C
      DO 802 JJ=1,NC		     
      J=JJ
C
C
      RFLECTOR(J)=RMOMENTZ(I,J)+RTT(I,J)*ROFSET(I)  ! AÑADIR DIMENSIONES VARIABLES
	RCORTANTE(J)=ABS(RLT(I,J))
      RTORSOR(J)=ABS(RMOMENTT(I,J))
C
C
      IF(RFLECTOR(J).GE.RFLEMAX)THEN
      RFLEMAX=RFLECTOR(J)
      ICAFLE=J
      END IF
C
C
      IF(RFLECTOR(J).LT.RFLEMIN)THEN
      RFLEMIN=RFLECTOR(J)
      IFLMIN=J
      END IF
C
C
      IF(RCORTANTE(J).GE.RCORMAX)THEN
      RCORMAX=RCORTANTE(J)
      ICACOR=J
      END IF
C
C
      IF(RTORSOR(J).GE.RTORMAX)THEN
      RTORMAX=RTORSOR(J)
      ICATOR=J
      END IF
C
C
      IF(RTT(I,J).GE.RAXMAX)THEN
      RAXMAX=RTT(I,J)
      IAXMA=J
      END IF
C
C
      IF(RTT(I,J).LT.RAXMIN)THEN
      RAXMIN=RTT(I,J)
      IAXMI=J
      END IF
C
C
  802 CONTINUE
C
      WRITE(12,3066)ICAFLE,RFLEMAX,RTT(I,ICAFLE),
     +RCORTANTE(ICAFLE),RLT(I,ICAFLE),RMOMENTT(I,ICAFLE),
     +RZT(I,ICAFLE),RMOMENTL(I,ICAFLE),
     +IFLMIN,RFLEMIN,RTT(I,IFLMIN),
     +RCORTANTE(IFLMIN),RLT(I,IFLMIN),RMOMENTT(I,IFLMIN),
     +RZT(I,IFLMIN),RMOMENTL(I,IFLMIN),
     +IAXMA,RFLECTOR(IAXMA),RAXMAX,
     +RCORTANTE(IAXMA),RLT(I,IAXMA),RMOMENTT(I,IAXMA),
     +RZT(I,IAXMA),RMOMENTL(I,IAXMA),
     +IAXMI,RFLECTOR(IAXMI),RAXMIN,
     +RCORTANTE(IAXMI),RLT(I,IAXMI),RMOMENTT(I,IAXMI),
     +RZT(I,IAXMI),RMOMENTL(I,IAXMI),
     +ICACOR,RFLECTOR(ICACOR),
     +RTT(I,ICACOR),RCORMAX,RLT(I,ICACOR),RMOMENTT(I,ICACOR),
     +RZT(I,ICACOR),RMOMENTL(I,ICACOR)
C
C
C 3066 FORMAT(3X,'   MZ  MAX.  ',3X,2F12.1,2F12.1,4X,I7,1X,4F13.1,/,
C     +3X,'   MZ  MIN.  ',3X,2F12.1,2F12.1,4X,I7,1X,4F13.1,/,
C     +3X,'  AXIAL MAX. ',3X,2F12.1,2F12.1,4X,I7,1X,4F13.1,/,
C     +3X,'  AXIAL MIN. ',3X,2F12.1,2F12.1,4X,I7,1X,4F13.1,/,
C     +3X,'CORTANTE MAX.',3X,2F12.1,2F12.1,4X,I7,1X,4F13.1,/,/)
C
C
C
 3066 FORMAT(3X,'   MZ  MAX.  ',2X,I3,2X,3F12.1,10X,4F12.1,/,
     +3X,'   MZ  MIN.  ',2X,I3,2X,3F12.1,10X,4F12.1,/,
     +3X,'  AXIAL MAX. ',2X,I3,2X,3F12.1,10X,4F12.1,/,
     +3X,'  AXIAL MIN. ',2X,I3,2X,3F12.1,10X,4F12.1,/,
     +3X,'CORTANTE MAX.',2X,I3,2X,3F12.1,10X,4F12.1,/,/)
C
C
C
C
C     WRITE(12,3065)J,RLT(I,J),RTT(I,J),RMOMENTZ(I,J),RZT(I,J), ! ESCRITURA ORIGINAL DE RESULTADOS
C    +RMOMENTT(I,J),RMOMENTL(I,J)
C
      GO TO 803
      END IF
C
C
C
C
C
	IF(INUMCASOS(I).LT.0)THEN      !NO IMPRIME LOS CASOS QUE SE QUITAN
C
C
C
      RFLEMAX=-1.0E35  ! MAXIMA FLEXION, TORSION Y FUERZA AXIAL
      RFLEMIN=1.0E35
      RTORMAX=-1.0E35
      RAXMAX=-1.0E35
      RAXMIN=1.0E35
      RCORMAX=-1.0E35
C
      ICAFLE=0    ! CASOS DE CARGA PARA LOS VALORES MAXIMOS
      IFLMIN=0
      ICATOR=0
      IAXMA=0
      IAXMI=0
      ICACOR=0
C
C
C
C
      DO 902 JJ=1,NC		     
      J=JJ
C
	DO 909 K=1,NUMCASOS(I)
	IF(NCAS(I,K).EQ.IICASE(J))GO TO 908
  909 CONTINUE
C
C
C
      RFLECTOR(J)=RMOMENTZ(I,J)+RTT(I,J)*ROFSET(I)  ! AÑADIR DIMENSIONES VARIABLES
	RCORTANTE(J)=ABS(RLT(I,J))
      RTORSOR(J)=ABS(RMOMENTT(I,J))
C
C
      IF(RFLECTOR(J).GE.RFLEMAX)THEN
      RFLEMAX=RFLECTOR(J)
      ICAFLE=J
      END IF
C
C
      IF(RFLECTOR(J).LT.RFLEMIN)THEN
      RFLEMIN=RFLECTOR(J)
      IFLMIN=J
      END IF
C
C
      IF(RCORTANTE(J).GE.RCORMAX)THEN
      RCORMAX=RCORTANTE(J)
      ICACOR=J
      END IF
C
C
      IF(RTORSOR(J).GE.RTORMAX)THEN
      RTORMAX=RTORSOR(J)
      ICATOR=J
      END IF
C
C
      IF(RTT(I,J).GE.RAXMAX)THEN
      RAXMAX=RTT(I,J)
      IAXMA=J
      END IF
C
C
      IF(RTT(I,J).LT.RAXMIN)THEN
      RAXMIN=RTT(I,J)
      IAXMI=J
      END IF
C
C
C
C
C
C      WRITE(12,3065)J,RLT(I,J),RTT(I,J),RMOMENTZ(I,J),RZT(I,J),
C     +RMOMENTT(I,J),RMOMENTL(I,J)
C
  908 CONTINUE
C
  902 CONTINUE
C
C
C      WRITE(12,3066)RFLEMAX,RTORSOR(ICAFLE),RTT(I,ICAFLE),
C     +RCORTANTE(ICAFLE),ICAFLE,RLT(I,ICAFLE),RZT(I,ICAFLE),
C     +RMOMENTL(I,ICAFLE),RFLECTOR(ICAFLE),
C     +RFLEMIN,RTORSOR(IFLMIN),RTT(I,IFLMIN),
C     +RCORTANTE(IFLMIN),IFLMIN,RLT(I,IFLMIN),RZT(I,IFLMIN),
C     +RMOMENTL(I,IFLMIN),RFLECTOR(IFLMIN),
C     +RFLECTOR(IAXMA),RTORSOR(IAXMA),RAXMAX,
C     +RCORTANTE(IAXMA),IAXMA,RLT(I,IAXMA),RZT(I,IAXMA),
C     +RMOMENTL(I,IAXMA),RFLECTOR(IAXMA),
C     +RFLECTOR(IAXMI),RTORSOR(IAXMI),RAXMIN,
C     +RCORTANTE(IAXMI),IAXMI,RLT(I,IAXMI),RZT(I,IAXMI),
C     +RMOMENTL(I,IAXMI),RFLECTOR(IAXMI),
C     +RFLECTOR(ICACOR),RTORSOR(ICACOR),
C     +RTT(I,ICACOR),RCORMAX,ICACOR,RLT(I,ICACOR),
C     +RZT(I,ICACOR),RMOMENTL(I,ICACOR),RFLECTOR(ICACOR)
C
      WRITE(12,3066)ICAFLE,RFLEMAX,RTT(I,ICAFLE),
     +RCORTANTE(ICAFLE),RLT(I,ICAFLE),RMOMENTT(I,ICAFLE),
     +RZT(I,ICAFLE),RMOMENTL(I,ICAFLE),
     +IFLMIN,RFLEMIN,RTT(I,IFLMIN),
     +RCORTANTE(IFLMIN),RLT(I,IFLMIN),RMOMENTT(I,IFLMIN),
     +RZT(I,IFLMIN),RMOMENTL(I,IFLMIN),
     +IAXMA,RFLECTOR(IAXMA),RAXMAX,
     +RCORTANTE(IAXMA),RLT(I,IAXMA),RMOMENTT(I,IAXMA),
     +RZT(I,IAXMA),RMOMENTL(I,IAXMA),
     +IAXMI,RFLECTOR(IAXMI),RAXMIN,
     +RCORTANTE(IAXMI),RLT(I,IAXMI),RMOMENTT(I,IAXMI),
     +RZT(I,IAXMI),RMOMENTL(I,IAXMI),
     +ICACOR,RFLECTOR(ICACOR),
     +RTT(I,ICACOR),RCORMAX,RLT(I,ICACOR),RMOMENTT(I,ICACOR),
     +RZT(I,ICACOR),RMOMENTL(I,ICACOR)
C
C
      GO TO 803
      END IF
C
C
C
C
      RFLEMAX=-1.0E35  ! MAXIMA FLEXION, TORSION Y FUERZA AXIAL
      RFLEMIN=1.0E35
      RTORMAX=-1.0E35
      RAXMAX=-1.0E35
      RAXMIN=1.0E35
      RCORMAX=-1.0E35
C
      ICAFLE=0    ! CASOS DE CARGA PARA LOS VALORES MAXIMOS
      IFLMIN=0
      ICATOR=0
      IAXMA=0
      IAXMI=0
      ICACOR=0
C
      NICAFLE=0    ! CASOS DE CARGA PARA LOS VALORES MAXIMOS
      NIFLMIN=0
      NICATOR=0
      NIAXMA=0
      NIAXMI=0
      NICACOR=0
C
C
C
C
      DO 804 JJ=1,NUMCASOS(I)
      J=JJ
C
      DO 801 K=J+1,NUMCASOS(I)       ! EVITA QUE SALGA '0.' CUANDO HAY CASOS
      IF(NCAS(I,K).EQ.NCAS(I,J))THEN ! DE CARGA REPETIDOS EN UNA MISMA
      J=K                            ! SECCION DEL FICHERO  .DAT
      END IF
  801 CONTINUE
C
C      NCASO=NCAS(I,J)
C
C
C      WRITE(12,3065)NCASO,RLT(I,J),RTT(I,J),RMOMENTO(I,J)
C 3065 FORMAT(8X,I3,5X,F16.2,4X,F16.2,4X,F16.2)
C
C
C     WRITE(12,3065)NCASO,RLT(I,J),RTT(I,J),RMOMENTZ(I,J),RZT(I,J),
C   +RMOMENTT(I,J),RMOMENTL(I,J)
C 3065 FORMAT(2X,I4,1X,F11.2,1X,F10.2,1X,F12.2,1X,F11.2,1X,F11.2,
C     +1X,F11.2)
C
C
  707	CONTINUE
C
      RFLECTOR(J)=RMOMENTZ(I,J)+RTT(I,J)*ROFSET(I)  ! AÑADIR DIMENSIONES VARIABLES
	RCORTANTE(J)=ABS(RLT(I,J))
      RTORSOR(J)=ABS(RMOMENTT(I,J))
C
C
      IF(RFLECTOR(J).GE.RFLEMAX)THEN
      RFLEMAX=RFLECTOR(J)
      ICAFLE=J
	NICAFLE=NCAS(I,J)
      END IF
C
C
      IF(RFLECTOR(J).LT.RFLEMIN)THEN
      RFLEMIN=RFLECTOR(J)
      IFLMIN=J
	NIFLMIN=NCAS(I,J)
      END IF
C
C
      IF(RCORTANTE(J).GE.RCORMAX)THEN
      RCORMAX=RCORTANTE(J)
      ICACOR=J
	NICACOR=NCAS(I,J)
      END IF
C
C
      IF(RTORSOR(J).GE.RTORMAX)THEN
      RTORMAX=RTORSOR(J)
      ICATOR=J
	NICATOR=NCAS(I,J)
      END IF
C
C
      IF(RTT(I,J).GE.RAXMAX)THEN
      RAXMAX=RTT(I,J)
      IAXMA=J
	NIAXMA=NCAS(I,J)
      END IF
C
C
      IF(RTT(I,J).LT.RAXMIN)THEN
      RAXMIN=RTT(I,J)
      IAXMI=J
	NIAXMI=NCAS(I,J)
      END IF
C
C
  804 CONTINUE
C
C
C
C      WRITE(12,3066)RFLEMAX,RTORSOR(ICAFLE),RTT(I,ICAFLE),
C     +RCORTANTE(ICAFLE),NICAFLE,RLT(I,ICAFLE),RZT(I,ICAFLE),
C     +RMOMENTL(I,ICAFLE),RFLECTOR(ICAFLE),
C     +RFLEMIN,RTORSOR(IFLMIN),RTT(I,IFLMIN),
C     +RCORTANTE(IFLMIN),NIFLMIN,RLT(I,IFLMIN),RZT(I,IFLMIN),
C     +RMOMENTL(I,IFLMIN),RFLECTOR(IFLMIN),
C     +RFLECTOR(IAXMA),RTORSOR(IAXMA),RAXMAX,
C     +RCORTANTE(IAXMA),NIAXMA,RLT(I,IAXMA),RZT(I,IAXMA),
C     +RMOMENTL(I,IAXMA),RFLECTOR(IAXMA),
C     +RFLECTOR(IAXMI),RTORSOR(IAXMI),RAXMIN,
C     +RCORTANTE(IAXMI),NIAXMI,RLT(I,IAXMI),RZT(I,IAXMI),
C     +RMOMENTL(I,IAXMI),RFLECTOR(IAXMI),
C     +RFLECTOR(ICACOR),RTORSOR(ICACOR),
C     +RTT(I,ICACOR),RCORMAX,NICACOR,RLT(I,ICACOR),
C     +RZT(I,ICACOR),RMOMENTL(I,ICACOR),RFLECTOR(ICACOR)
C
      WRITE(12,3066)NICAFLE,RFLEMAX,RTT(I,ICAFLE),
     +RCORTANTE(ICAFLE),RLT(I,ICAFLE),RMOMENTT(I,ICAFLE),
     +RZT(I,ICAFLE),RMOMENTL(I,ICAFLE),
     +NIFLMIN,RFLEMIN,RTT(I,IFLMIN),
     +RCORTANTE(IFLMIN),RLT(I,IFLMIN),RMOMENTT(I,IFLMIN),
     +RZT(I,IFLMIN),RMOMENTL(I,IFLMIN),
     +NIAXMA,RFLECTOR(IAXMA),RAXMAX,
     +RCORTANTE(IAXMA),RLT(I,IAXMA),RMOMENTT(I,IAXMA),
     +RZT(I,IAXMA),RMOMENTL(I,IAXMA),
     +NIAXMI,RFLECTOR(IAXMI),RAXMIN,
     +RCORTANTE(IAXMI),RLT(I,IAXMI),RMOMENTT(I,IAXMI),
     +RZT(I,IAXMI),RMOMENTL(I,IAXMI),
     +NICACOR,RFLECTOR(ICACOR),
     +RTT(I,ICACOR),RCORMAX,RLT(I,ICACOR),RMOMENTT(I,ICACOR),
     +RZT(I,ICACOR),RMOMENTL(I,ICACOR)
C
  803 CONTINUE
C
C
C
C   ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
C
C
C
C
  808 CONTINUE
  800 CONTINUE
C 
C
C
C     ESCRIBE LA IDENTIFICACION DE LOS CASOS DE CARGA
C     ===============================================
C
C*****************************
C
      WRITE(12,3070)
 3070 FORMAT(/,/,/,/,2X,'IDENTIFICACION DE LOS CASOS DE CARGA',/)
C
      DO 806 I=1,NUMSEC         ! SI SE PONE 0 EN EL NUMERO DE CASOS DE UNA SECCION
      IF(INUMCASOS(I).LE.0)THEN  ! CASOS DE CARGA CON NUMEROS NEGATIVO
      DO 811 J=1,NC
  811 WRITE(12,3075)J,IICASE(J),CASO(J)
      GO TO 812
      END IF
  806 CONTINUE
C
C
C
      DO 805 I=1,NUMSEC
      DO 805 J=1,NUMCASOS(I)
      DO 805 K=1,NC
C
      IF(NCAS(I,J).EQ.K)ICASEL(K)=1
C
C*************************************
C      WRITE(12,3071)I,J,K,NCAS(I,J),ICASEL(K)
C 3071 FORMAT(2X,'I=',I2,2X,'J=',I2,2X,'K=',I2,2X,'NCAS:',I3,
C     +2X,'ICASEL=',I2)
C*************************************

C
  805 CONTINUE
C
C
C
      DO 810 I=1,NC
C
      IF(ICASEL(I).EQ.1)THEN
      WRITE(12,3075)I,IICASE(I),CASO(I)
 3075 FORMAT(2X,I4,5X,'SUB:',I8,5X,A40)
      END IF
C
  810 CONTINUE
C
  812 CONTINUE
C
      END
